[package]
name              = "bones_volleyball"
version           = "0.1.0"
publish           = false
edition            = "2021"

[profile.dev]
opt-level = 1

[dependencies]
bones_framework     = { git = "https://github.com/fishfolk/bones", rev = "fc00c0c9aeceea2c2836c6568bdcf7b202c20694", features = ["net-debug"] }
bones_bevy_renderer = { git = "https://github.com/fishfolk/bones", rev = "fc00c0c9aeceea2c2836c6568bdcf7b202c20694" }
bytemuck = "1.16.1"

[dependencies.ttf-parser]
version = "0.24.1"
features = ["std"]
