[package]
name              = "bones_volleyball"
version           = "0.1.0"
publish           = false
edition            = "2021"

[profile.dev]
opt-level = 1

[dependencies]
bones_framework     = { git = "https://github.com/fishfolk/bones", rev = "885d51d0c6a38b506ee988beb68708c7970a8d53", features = ["net-debug"] }
bones_bevy_renderer = { git = "https://github.com/fishfolk/bones", rev = "885d51d0c6a38b506ee988beb68708c7970a8d53" }
bytemuck = "1.16.1"

[dependencies.ttf-parser]
version = "0.24.1"
features = ["std"]
